##.......................chapter 4 workout....................................
#.........................map()......add 2 list using map and lambda.........................
"""num1 = [1,2,3]
num2 = [4,5,6]
result = map(lambda x,y : x + y, num1, num2)
print(list(result))"""

#...
